#!/usr/bin/perl

use strict;
use File::Find;
use File::Path;

my ($original, $replace);

$replace = qq[mysql:dbname=rinatours1]; $original = q[mysql:dbname=rinatours];
print "We have: $original, $replace\n";
find(\&replace_line, "rinatours2");

sub replace_line
{
	my ($file, $line, @our_file);

	$file = $_;
	open (MYFILE, $file);
	while(<MYFILE>)
	{
		$line = $_;
		$line =~ s/$original/$replace/g;
		push(@our_file, $line);
	}
	close MYFILE;
	
	open (WRITEFILE, ">$file");
	foreach $line (@our_file)
	{
		print WRITEFILE $line;
	}
	close WRITEFILE;
}

